docker push saintjames95/hadoop:med_v1_1pct_master_s
docker push saintjames95/hadoop:med_v1_1pct_s1_s
docker push saintjames95/hadoop:med_v1_1pct_s2_s
docker push saintjames95/hadoop:med_v1_1pct_s3_s
docker push saintjames95/hadoop:med_v1_1pct_s4_s
