apiVersion: v1
kind: Pod
metadata:
  name: hadoop1-master
  labels:
    app: run1
spec:
  subdomain: hadoop
  hostname: hadoop1-master
  containers:
  - name: hadoop1-master
    image: saintjames95/hadoop:master
    command: ["/bin/sh"]
    args: ["-c", "service ssh start && sleep infinity"]