apiVersion: v1
kind: Pod
metadata:
  name: hadoop-slave1
  labels:
    app: run1
spec:
  subdomain: hadoop
  hostname: hadoop1-slave1
  containers:
  - name: hadoop-slave1
    image: saintjames95/hadoop:slave
    command: ["/bin/sh"]
    args: ["-c", "service ssh start && sleep infinity"]